apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalaserver
spec:
  selector:
    matchLabels:
      app: scalaserver
  template:
    metadata:
      labels:
        app: scalaserver
    spec:
      containers:
        - name: scalaserver
          image: httpserver:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 3997
